# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

def find_the_difference(s, t)
    sorted_s = s.split("").sort
    sorted_t = t.split("").sort
    difference = ""
    
    sorted_t.each_with_index do |letter, idx|
        if letter != sorted_s[idx]
            difference = letter
            break
        end
    end
    difference
end